[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://api.emailjs.com https://cdnjs.cloudflare.com https://kit.fontawesome.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https: https://kit.fontawesome.com https://cdn.jsdelivr.net;
      connect-src 'self' https://api.emailjs.com https://fonts.googleapis.com https://fonts.gstatic.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net;
      object-src 'none';
      frame-src 'none';
      frame-ancestors 'self'; # Prevent unauthorized framing
      base-uri 'self';
      upgrade-insecure-requests;
    """
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
